package com.schwarz.kokain.ksp.generation

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSFile
import com.squareup.kotlinpoet.FileSpec
import java.io.IOException

class KokainCodeGenerator(private val generator: CodeGenerator) {

    @Throws(IOException::class)
    fun generate(toGenerate: FileSpec, containingFile: List<KSFile>, aggregating: Boolean = false) {

        val fileWithHeader = toGenerate.toBuilder().addFileComment(HEADER).build()
        generator.createNewFile(
            Dependencies(aggregating, *containingFile.toTypedArray()),
            fileWithHeader.packageName,
            fileWithHeader.name
        )
            .writer()
            .use { fileWithHeader.writeTo(it) }
    }

    companion object {

        private val HEADER = (
            "DO NOT EDIT THIS FILE.\n" +
                "Generated using Kokain KSP \n\n" +
                "Do not edit this class!!!!.\n"
            )
    }
}
