package com.schwarz.kokain.ksp.generation

import com.google.devtools.ksp.processing.CodeGenerator
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.ksp.writeTo
import java.io.IOException

class KokainCodeGenerator(private val generator: CodeGenerator) {

    @Throws(IOException::class)
    fun generate(entityToGenerate: FileSpec) {

        val fileWithHeader = entityToGenerate.toBuilder().addFileComment(HEADER).build()
        fileWithHeader.writeTo(generator, false)
    }

    companion object {
        private const val HEADER = (
                "DO NOT EDIT THIS FILE.\n" +
                        "Generated using Kokain KSP \n\n" +
                        "Do not edit this class!!!!.\n"
                )
    }
}
